<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dorosak.MediaWorker\Dorosak.MediaWorker.csproj" />
  </ItemGroup>

  <Import Project="..\TestProject.Common.props" />

</Project>
