<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dorosak.Application\Dorosak.Application.csproj" />
    <ProjectReference Include="..\..\src\Dorosak.Infrastructure\Dorosak.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Dorosak.MediaWorker\Dorosak.MediaWorker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\deploy\neon\bootstrap-development-database.sql"
          Link="bootstrap-development-database.sql"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Import Project="..\TestProject.Common.props" />

</Project>
