// <auto-generated />
using System;
using Dorosak.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dorosak.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DorosakDbContext))]
    [Migration("20260806223946_Phase5IdentitySecurity")]
    partial class Phase5IdentitySecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dorosak.Domain.Identity.MfaChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfa_challenges");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_mfa_challenges_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mfa_challenges_user_id");

                    b.ToTable("mfa_challenges", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_mfa_challenges_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_mfa_challenges_expiration", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.MfaRecoveryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfa_recovery_codes");

                    b.HasIndex("UserId", "CodeHash")
                        .IsUnique()
                        .HasDatabaseName("uq_mfa_recovery_codes_user_hash");

                    b.ToTable("mfa_recovery_codes", "identity");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.RefreshSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at");

                    b.Property<string>("AuthenticationMethods")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("authentication_methods");

                    b.Property<int>("AuthorizationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("device_name");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset>("IdleExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idle_expires_at");

                    b.Property<string>("IpAddressHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address_hash");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_sessions");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_sessions_family_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_sessions_user_id");

                    b.HasIndex("UserId", "RevokedAt", "AbsoluteExpiresAt")
                        .HasDatabaseName("ix_refresh_sessions_active_user");

                    b.ToTable("refresh_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_sessions_authorization_version", "authorization_version > 0");

                            t.HasCheckConstraint("ck_refresh_sessions_expiration", "idle_expires_at <= absolute_expires_at");
                        });
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiration", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("IpAddressHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address_hash");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_events");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_security_events_session_id");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_security_events_user_occurred_at");

                    b.ToTable("security_events", "identity");
                });

            modelBuilder.Entity("Dorosak.Domain.Operations.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("response_schema_version");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Scope", "Operation", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotency_records_scope_operation_key");

                    b.ToTable("idempotency_records", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_idempotency_records_response_schema_version", "response_schema_version > 0");
                        });
                });

            modelBuilder.Entity("Dorosak.Domain.Operations.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("event_type");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_error_code");

                    b.Property<Guid?>("LockToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_token");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("LockedUntil")
                        .HasDatabaseName("ix_outbox_messages_locked_until")
                        .HasFilter("processed_at IS NULL AND locked_until IS NOT NULL");

                    b.HasIndex("AvailableAt", "OccurredAt", "Id")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_schema_version", "schema_version > 0");
                        });
                });

            modelBuilder.Entity("Dorosak.Domain.Profiles.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", "profiles");
                });

            modelBuilder.Entity("Dorosak.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_identity_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_identity_roles_normalized_name")
                        .HasFilter("normalized_name IS NOT NULL");

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001"),
                            ConcurrencyStamp = "018f3f0e43807b1b8f8db8ea9c546001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002"),
                            ConcurrencyStamp = "018f3f0e43807b1b8f8db8ea9c546002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003"),
                            ConcurrencyStamp = "018f3f0e43807b1b8f8db8ea9c546003",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Dorosak.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<int>("AuthorizationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("authorization_version");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long?>("LastMfaTimeStep")
                        .HasColumnType("bigint")
                        .HasColumnName("last_mfa_time_step");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("ProtectedMfaSecret")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("protected_mfa_secret");

                    b.Property<string>("ProtectedPendingMfaSecret")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("protected_pending_mfa_secret");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("security_stamp");

                    b.Property<int>("SecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("security_version");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_identity_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_identity_users_normalized_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("uq_identity_users_normalized_user_name")
                        .HasFilter("normalized_user_name IS NOT NULL");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "operations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_role_claims_role_id");

                    b.HasIndex("RoleId", "ClaimType", "ClaimValue")
                        .IsUnique()
                        .HasDatabaseName("uq_identity_role_claims_role_type_value");

                    b.ToTable("role_claims", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permission",
                            ClaimValue = "Profile.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permission",
                            ClaimValue = "Profile.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permission",
                            ClaimValue = "Security.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permission",
                            ClaimValue = "Sessions.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permission",
                            ClaimValue = "TeacherApplication.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permission",
                            ClaimValue = "Learning.AccessOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "permission",
                            ClaimValue = "Progress.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permission",
                            ClaimValue = "Quiz.AttemptOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permission",
                            ClaimValue = "Assignment.SubmitOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permission",
                            ClaimValue = "Review.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permission",
                            ClaimValue = "Discussion.Participate",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permission",
                            ClaimValue = "Comment.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permission",
                            ClaimValue = "Message.SendAsSelf",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permission",
                            ClaimValue = "Conversation.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permission",
                            ClaimValue = "Notification.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.VerifyPublic",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "permission",
                            ClaimValue = "Order.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permission",
                            ClaimValue = "Checkout.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "permission",
                            ClaimValue = "Subscription.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546001")
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "permission",
                            ClaimValue = "Profile.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "permission",
                            ClaimValue = "Profile.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permission",
                            ClaimValue = "Security.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "permission",
                            ClaimValue = "Sessions.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "permission",
                            ClaimValue = "TeacherApplication.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permission",
                            ClaimValue = "Learning.AccessOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 31,
                            ClaimType = "permission",
                            ClaimValue = "Progress.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 32,
                            ClaimType = "permission",
                            ClaimValue = "Quiz.AttemptOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 33,
                            ClaimType = "permission",
                            ClaimValue = "Assignment.SubmitOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 34,
                            ClaimType = "permission",
                            ClaimValue = "Review.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 35,
                            ClaimType = "permission",
                            ClaimValue = "Discussion.Participate",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 36,
                            ClaimType = "permission",
                            ClaimValue = "Comment.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 37,
                            ClaimType = "permission",
                            ClaimValue = "Message.SendAsSelf",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 38,
                            ClaimType = "permission",
                            ClaimValue = "Conversation.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 39,
                            ClaimType = "permission",
                            ClaimValue = "Notification.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 40,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 41,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.VerifyPublic",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 42,
                            ClaimType = "permission",
                            ClaimValue = "Order.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 43,
                            ClaimType = "permission",
                            ClaimValue = "Checkout.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 44,
                            ClaimType = "permission",
                            ClaimValue = "Subscription.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 45,
                            ClaimType = "permission",
                            ClaimValue = "Course.Create",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 46,
                            ClaimType = "permission",
                            ClaimValue = "Course.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 47,
                            ClaimType = "permission",
                            ClaimValue = "Course.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 48,
                            ClaimType = "permission",
                            ClaimValue = "Course.DeleteOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 49,
                            ClaimType = "permission",
                            ClaimValue = "Course.SubmitOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 50,
                            ClaimType = "permission",
                            ClaimValue = "Media.UploadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 51,
                            ClaimType = "permission",
                            ClaimValue = "Media.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 52,
                            ClaimType = "permission",
                            ClaimValue = "Learning.ViewCourseLearners",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 53,
                            ClaimType = "permission",
                            ClaimValue = "Submission.GradeCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 54,
                            ClaimType = "permission",
                            ClaimValue = "Assessment.ManageCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 55,
                            ClaimType = "permission",
                            ClaimValue = "Announcement.ManageCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 56,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ReadEarningsOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 57,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ManagePayoutAccountOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546002")
                        },
                        new
                        {
                            Id = 58,
                            ClaimType = "permission",
                            ClaimValue = "Profile.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 59,
                            ClaimType = "permission",
                            ClaimValue = "Profile.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 60,
                            ClaimType = "permission",
                            ClaimValue = "Security.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 61,
                            ClaimType = "permission",
                            ClaimValue = "Sessions.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 62,
                            ClaimType = "permission",
                            ClaimValue = "TeacherApplication.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 63,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 64,
                            ClaimType = "permission",
                            ClaimValue = "Enrollment.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 65,
                            ClaimType = "permission",
                            ClaimValue = "Learning.AccessOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 66,
                            ClaimType = "permission",
                            ClaimValue = "Progress.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 67,
                            ClaimType = "permission",
                            ClaimValue = "Quiz.AttemptOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 68,
                            ClaimType = "permission",
                            ClaimValue = "Assignment.SubmitOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 69,
                            ClaimType = "permission",
                            ClaimValue = "Review.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 70,
                            ClaimType = "permission",
                            ClaimValue = "Discussion.Participate",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 71,
                            ClaimType = "permission",
                            ClaimValue = "Comment.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 72,
                            ClaimType = "permission",
                            ClaimValue = "Message.SendAsSelf",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 73,
                            ClaimType = "permission",
                            ClaimValue = "Conversation.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 74,
                            ClaimType = "permission",
                            ClaimValue = "Notification.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 75,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 76,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.VerifyPublic",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 77,
                            ClaimType = "permission",
                            ClaimValue = "Order.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 78,
                            ClaimType = "permission",
                            ClaimValue = "Checkout.CreateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 79,
                            ClaimType = "permission",
                            ClaimValue = "Subscription.ManageOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 80,
                            ClaimType = "permission",
                            ClaimValue = "Course.Create",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 81,
                            ClaimType = "permission",
                            ClaimValue = "Course.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 82,
                            ClaimType = "permission",
                            ClaimValue = "Course.UpdateOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 83,
                            ClaimType = "permission",
                            ClaimValue = "Course.DeleteOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 84,
                            ClaimType = "permission",
                            ClaimValue = "Course.SubmitOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 85,
                            ClaimType = "permission",
                            ClaimValue = "Media.UploadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 86,
                            ClaimType = "permission",
                            ClaimValue = "Media.ReadOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 87,
                            ClaimType = "permission",
                            ClaimValue = "Learning.ViewCourseLearners",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 88,
                            ClaimType = "permission",
                            ClaimValue = "Submission.GradeCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 89,
                            ClaimType = "permission",
                            ClaimValue = "Assessment.ManageCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 90,
                            ClaimType = "permission",
                            ClaimValue = "Announcement.ManageCourse",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 91,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ReadEarningsOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 92,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ManagePayoutAccountOwn",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 93,
                            ClaimType = "permission",
                            ClaimValue = "TeacherApplication.ReviewAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 94,
                            ClaimType = "permission",
                            ClaimValue = "Course.ReviewAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 95,
                            ClaimType = "permission",
                            ClaimValue = "Course.PublishAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 96,
                            ClaimType = "permission",
                            ClaimValue = "Course.ManageAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 97,
                            ClaimType = "permission",
                            ClaimValue = "Media.ManageAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 98,
                            ClaimType = "permission",
                            ClaimValue = "Moderation.ReviewAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 99,
                            ClaimType = "permission",
                            ClaimValue = "Certificate.RevokeAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 100,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ManageOffers",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 101,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ManageOrders",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 102,
                            ClaimType = "permission",
                            ClaimValue = "Commerce.ManageRefunds",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 103,
                            ClaimType = "permission",
                            ClaimValue = "User.ReadAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 104,
                            ClaimType = "permission",
                            ClaimValue = "User.ManageAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 105,
                            ClaimType = "permission",
                            ClaimValue = "Role.ManageAny",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 106,
                            ClaimType = "permission",
                            ClaimValue = "Catalog.ManageTaxonomy",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 107,
                            ClaimType = "permission",
                            ClaimValue = "Cms.Manage",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 108,
                            ClaimType = "permission",
                            ClaimValue = "Settings.Manage",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 109,
                            ClaimType = "permission",
                            ClaimValue = "FeatureFlag.Manage",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 110,
                            ClaimType = "permission",
                            ClaimValue = "Analytics.Read",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        },
                        new
                        {
                            Id = 111,
                            ClaimType = "permission",
                            ClaimValue = "Audit.Read",
                            RoleId = new Guid("018f3f0e-4380-7b1b-8f8d-b8ea9c546003")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identity_user_claims_user_id");

                    b.ToTable("user_claims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_identity_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identity_user_logins_user_id");

                    b.ToTable("user_logins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_identity_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_identity_user_roles_role_id");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_identity_user_tokens");

                    b.ToTable("user_tokens", "identity");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.MfaChallenge", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_challenges_users_user_id");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.MfaRecoveryCode", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfa_recovery_codes_users_user_id");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.RefreshSession", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_sessions_users_user_id");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Dorosak.Domain.Identity.RefreshSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_sessions_session_id");
                });

            modelBuilder.Entity("Dorosak.Domain.Identity.SecurityEvent", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_security_events_users_user_id");
                });

            modelBuilder.Entity("Dorosak.Domain.Profiles.UserProfile", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Dorosak.Domain.Profiles.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Dorosak.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
